### ISSUE TITLE
アイコン案

### ISSUE THREAD

**Issue by momeroku** [momerio/meigen_generator#7]
## テーマカラーについて
#EC9A23
https://github.com/momerio/meigen_generator/issues/6 参照

## 要件
- 生成される感じ=歯車のイメージ
- 『名』もしくは『名言』もしくは『名言生成』もしくは『名言自動生成』の文字をいれる

**Comment by momeroku** [comment]
![image](https://user-images.githubusercontent.com/84517709/140638354-91f7bf6c-e4a2-45db-ba90-15d6ca665021.png)

どっかの学校の校章みたいになってしまった……orz

**Comment by parsecmonkey** [comment]
# 没で

**Comment by momeroku** [comment]
# じゃあ，作成に掛かった1分くらいを返して

**Comment by parsecmonkey** [comment]
![meigen_generator_logo](https://user-images.githubusercontent.com/60334704/140642432-7e9e6df7-0e82-45e3-88ee-9cd9f20e9c87.png)
作りました。

**Comment by momeroku** [comment]
# 採用

**Comment by momeroku** [comment]
文字順は左上からのほうがいいかな?

名言
生成

みたいに

**Comment by parsecmonkey** [comment]
![ic_launcher](https://user-images.githubusercontent.com/60334704/140642809-b5be827a-d212-4886-bd3b-b45b47fe6e7d.png)
修正

**Comment by momeroku** [comment]
完璧
